[package]
name = "tisty-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }

[lib]
name = "tisty_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { workspace = true }

[target."cfg(windows)".dependencies]
winreg = "0.55"

[dependencies]
tisty-core.workspace = true
tisty-sync.workspace = true
tisty-nl.workspace = true
tauri.workspace = true
tauri-plugin-opener.workspace = true
tauri-plugin-dialog.workspace = true
tauri-plugin-global-shortcut.workspace = true
tauri-plugin-notification.workspace = true
tauri-plugin-single-instance.workspace = true
sys-locale.workspace = true
serde.workspace = true
serde_json.workspace = true
jiff.workspace = true
ulid.workspace = true
zip.workspace = true
semver = "1"
reqwest = { version = "0.13", default-features = false, features = ["blocking", "default-tls", "charset", "http2"] }

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
